In [1]:
import numpy as np
import pandas as pd

In [4]:
f_metrics=pd.read_csv("C:\\Users\perum\Desktop\Code Basics Projects\AtliQo Telecom 5G\C3 Input_for_Participants\\fact_atliqo_metrics.csv")
f_metrics.head()

,date,city_code,company,atliqo_revenue_crores,arpu,active_users_lakhs,unsubscribed_users_lakhs
0,01-Jan-22,400001,Atliqo,60.69,192,31.61,1.90
1,01-Jan-22,110001,Atliqo,42.71,175,24.41,1.31
2,01-Jan-22,700001,Atliqo,36.91,175,21.09,1.25
3,01-Jan-22,560001,Atliqo,37.40,175,21.37,1.39
4,01-Jan-22,600001,Atliqo,30.80,203,15.17,1.12

In [5]:
f_metrics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   date                      120 non-null    object
 1   city_code                 120 non-null    int64
 2   company                   120 non-null    object
 3   atliqo_revenue_crores     120 non-null    float64
 4   arpu                      120 non-null    int64
 5   active_users_lakhs        120 non-null    float64
 6   unsubscribed_users_lakhs  120 non-null    float64
dtypes: float64(3), int64(2), object(2)
memory usage: 6.7+ KB

In [6]:
f_metrics.isnull().sum()

date                        0
city_code                   0
company                     0
atliqo_revenue_crores       0
arpu                        0
active_users_lakhs          0
unsubscribed_users_lakhs    0
dtype: int64

In [9]:
f_metrics.columns

Index(['date', 'city_code', 'company', 'atliqo_revenue_crores', 'arpu',
       'active_users_lakhs', 'unsubscribed_users_lakhs'],
      dtype='object')

In [14]:
f_metrics = f_metrics.rename(columns={'active_users_lakhs':'active_users'})

In [15]:
f_metrics = f_metrics.rename(columns={'unsubscribed_users_lakhs':'unsubscribed_users'})

In [16]:
f_metrics.columns

Index(['date', 'city_code', 'company', 'atliqo_revenue_crores', 'arpu',
       'active_users', 'unsubscribed_users'],
      dtype='object')

In [17]:
f_market_share=pd.read_csv("C:\\Users\perum\Desktop\Code Basics Projects\AtliQo Telecom 5G\C3 Input_for_Participants\\fact_market_share.csv")
f_market_share.head()

        date  city_code  tmv_city_crores company  ms_pct
0  01-Jan-22     400001           286.29  Atliqo   21.20
1  01-Jan-22     110001           241.59  Atliqo   17.68
2  01-Jan-22     700001           222.19  Atliqo   16.61
3  01-Jan-22     560001           195.41  Atliqo   19.14
4  01-Jan-22     600001           166.78  Atliqo   18.47

In [18]:
f_market_share.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             600 non-null    object
 1   city_code        600 non-null    int64
 2   tmv_city_crores  600 non-null    float64
 3   company          600 non-null    object
 4   ms_pct           600 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 23.6+ KB

In [22]:
f_market_share.describe().round(2)

       city_code  tmv_city_crores  ms_pct
count     600.00           600.00  600.00
mean   426935.87           138.40   20.00
std    206835.71            92.86   10.94
min    110001.00            17.55    5.35
25%    226001.00            57.94    9.09
50%    411001.00           124.85   18.23
75%    600001.00           209.36   31.00
max    800008.00           349.97   41.46

In [20]:
f_market_share.isnull().sum()

date               0
city_code          0
tmv_city_crores    0
company            0
ms_pct             0
dtype: int64

In [21]:
f_market_share.columns

Index(['date', 'city_code', 'tmv_city_crores', 'company', 'ms_pct'], dtype='object')

In [25]:
f_plan_revenue=pd.read_csv("C:\\Users\perum\Desktop\Code Basics Projects\AtliQo Telecom 5G\C3 Input_for_Participants\\fact_plan_revenue.csv")
f_plan_revenue.head()

        date  city_code plans  plan_revenue_crores
0  01-Jan-22     400001    p1                 6.26
1  01-Jan-22     110001    p1                 4.58
2  01-Jan-22     700001    p1                 4.29
3  01-Jan-22     560001    p1                 4.26
4  01-Jan-22     600001    p1                 3.60

In [26]:
f_plan_revenue.isnull().sum()

date                   0
city_code              0
plans                  0
plan_revenue_crores    0
dtype: int64

In [27]:
d_cities=pd.read_csv("C:\\Users\perum\Desktop\Code Basics Projects\AtliQo Telecom 5G\C3 Input_for_Participants\\dim_cities.csv")
d_cities.head()

   city_code  city_name
0     400001     Mumbai
1     110001      Delhi
2     700001    Kolkata
3     560001  Bangalore
4     600001    Chennai

In [28]:
d_date=pd.read_csv("C:\\Users\perum\Desktop\Code Basics Projects\AtliQo Telecom 5G\C3 Input_for_Participants\dim_date.csv")
d_date.head()

        date month_name before/after_5g  time_period
0  01-Jan-22        Jan       Before 5G            1
1  01-Feb-22        Feb       Before 5G            2
2  01-Mar-22        Mar       Before 5G            3
3  01-Apr-22        Apr       Before 5G            4
4  01-Jun-22        Jun        After 5G            1

In [29]:
d_date.isnull().sum()

date               0
month_name         0
before/after_5g    0
time_period        0
dtype: int64

In [30]:
d_plan=pd.read_csv("C:\\Users\perum\Desktop\Code Basics Projects\AtliQo Telecom 5G\C3 Input_for_Participants\dim_plan.csv")
d_plan.head()

  plan                                   plan_description
0   p1  Smart Recharge Pack (2 GB / Day Combo For 3 mo...
1   p2  Super Saviour Pack (1.5 GB / Day Combo For 56 ...
2   p3        Elite saver Pack (1 GB/ Day) Valid: 28 Days
3   p4  Mini Data Saver Pack (500 MB/ Day) Valid: 20 Days
4   p5                    Rs. 99 Full Talktime Combo Pack

In [31]:
d_plan.isnull().sum()

plan                0
plan_description    0
dtype: int64

In [33]:
# Loading the Datasets into sql using Mysql+pymysql

from sqlalchemy import create_engine
from urllib.parse import quote_plus

host="localhost"
port="3306"
database="telecom"
user="root"
password= quote_plus("Password@123")

engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")

metrics="fact_atliqo_metrics"
f_metrics.to_sql(metrics,engine, if_exists="replace",index=False)

print(f"Successfully loaded the table {metrics} in database {database}.")

Successfully loaded the table fact_atliqo_metrics in database telecom.

In [34]:
market="fact_market_share"
f_market_share.to_sql(market,engine,if_exists="replace", index=False)
print(f"Successfully loaded the table {market} in database {database}.")

Successfully loaded the table fact_market_share in database telecom.

In [35]:
plan="fact_plan_revenue"
f_plan_revenue.to_sql(plan,engine,if_exists="replace",index=False)
print(f"Successfully loaded the table {plan} in database {database}.")

Successfully loaded the table fact_plan_revenue in database telecom.

In [36]:
city="dim_cities"
d_cities.to_sql(city,engine,if_exists="replace",index=False)
print(f"Successfully loaded the table {plan} in database {database}.")

Successfully loaded the table fact_plan_revenue in database telecom.

In [37]:
date="dim_date"
d_date.to_sql(date,engine,if_exists="replace",index=False)
print(f"Successfully loaded the table {date} in database {database}.")

Successfully loaded the table dim_date in database telecom.

In [38]:
plans="dim_plan"
d_plan.to_sql(plans,engine,if_exists="replace",index=False)
print(f"Successfully loaded the table {plans} in database {database}.")

Successfully loaded the table dim_plan in database telecom.